### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by checchia** [wavesnode/gateway-for-woocommerce#19]
After install, error 500. In nginx log:

*116 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected end of file in /home/wpuser/sites/cryptolab/wp-content/plugins/gateway-for-woocommerce/includes/class-waves-gateway.php on line 238"

**Comment by clipto** [comment]
See our blogpost:
https://wavesnode.net/blog/waves-woocommerce-gateway/

PHP Parse error: syntax error, unexpected end of file
If you see this error on a white page after activating the plugin:

Got error ‘PHP message: PHP Parse error: syntax error, unexpected end of file in /../wp-content/plugins/waves-gateway-for-woocommerce/includes/class-waves-gateway.php on line XXXX

This is probably caused by the PHP settings, as we use short-tags in our software.
In the last PHP versions this is probably disabled by default.

To resolve:

Open php.ini and set
short_open_tag=On
